/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
export var styles = ['div[_ngcontent-%COMP%] {\n  font-size: 14px;\n  color: #000;\n  font-family: Arial,Helvetica,sans-serif;\n  line-height: 1.4;\n  max-width: 500px\n}'];
//# sourceMappingURL=main.css.shim.ngstyle.js.map