/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['div[_ngcontent-%COMP%] {\n  font-size: 14px;\n  color: #000;\n  font-family: Arial,Helvetica,sans-serif;\n  line-height: 1.4;\n  max-width: 500px\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvbGllemxzYW50b3MvcHJvamVjdC9zYW1wbGUtaTE4bi9zcmMvYXBwL21haW4uY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL2hvbWUvbGllemxzYW50b3MvcHJvamVjdC9zYW1wbGUtaTE4bi9zcmMvYXBwL21haW4uY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
